# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CCUILayout' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 pod 'Masonry', '~> 1.1.0'
 pod 'MJExtension', '~> 3.2.1'
 pod 'MJRefresh', '~> 3.2.2'

  # Pods for CCUILayout

end
